# Use the official MongoDB image
FROM mongo:7.0
# Using latest is not best pracitce and not suitable for prod env

# Expose the default MongoDB port
EXPOSE 27017

# Set the MongoDB data directory and keyfile directory as volumes
#VOLUME ["/data/db", "/etc/mongodb-keyfile"]
VOLUME ["/data/db"]


